itk-dev/os2loop

- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/comment--os2loop-post-comments.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/comment--os2loop-question-answers.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/field--node--os2loop-question-answers.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/field--os2loop-post-comments.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/links--comment.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-document.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-external.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-page.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-post.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-question.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/menu-local-task.html.twig
https://jira.itkdev.dk/browse/LOOP-832
Cleans up whitespace in templates to match `.editorconfig` settings.
> LOOP-832: Cleaned up whitespace in templates

- composer.json
- composer.lock
- config/sync/core.entity_form_display.node.os2loop_documents_collection.default.yml
- config/sync/core.entity_form_display.node.os2loop_documents_document.default.yml
- config/sync/core.entity_form_display.node.os2loop_external.default.yml
- config/sync/core.entity_form_display.node.os2loop_post.default.yml
- config/sync/core.entity_form_display.node.os2loop_question.default.yml
- config/sync/core.entity_form_display.user.user.default.yml
- config/sync/core.extension.yml
https://jira.itkdev.dk/browse/LOOP-832
Adds [Autocomplete deluxe](https://www.drupal.org/project/autocomplete_deluxe) to taxonomy fields.
Makes order of taxonomy fields consistent.
> LOOP-832: Added  Autocomplete deluxe to taxonomy fields

- web/profiles/custom/os2loop/modules/os2loop_upvote/src/Helper/FlagHelper.php
https://jira.itkdev.dk/browse/LOOP-800
"I os2loop_upvote modulet ligger FlagHelper-klassen med preprocessField() metoden. Denne metode har en ret høj kodekompleksitet med mange betingelser og løkker nested i hinanden. Dette nedsætter læsbarheden og øger risikoen for fejl i funktionaliteten, samt øger risikoen for at der ved videreudvikling introduceres nye fejl eller utilsigtet, ændret logik.
Der er muligvis allerede en fejl i metoden idet nedenstående linje muligvis kan udføres uden der er identificeret / sat en $top_comment. Om det i praksis er et problem skal jeg ikke kunne sige, men det illustrerer meget fint hvorfor det kan være en idé at arbejde med metoden så den bliver mere læsbar.
Samlet set er metoden dog ikke omfattende hvilket afbøder risikoen en smule."
> LOOP-800: added comments and fixed errors in flaghelper

- web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.module
- web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/FormHelper.php
- web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/NodeHelper.php
- web/profiles/custom/os2loop/modules/os2loop_search_db/os2loop_search_db.module
- web/profiles/custom/os2loop/modules/os2loop_search_db/src/Helper/SearchApiAutocompleteHelper.php
- web/profiles/custom/os2loop/modules/os2loop_upvote/os2loop_upvote.module
- web/profiles/custom/os2loop/os2loop.profile
- web/profiles/custom/os2loop/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-844
Adds descriptions of why we implement hooks.
> LOOP-844: Changes after external code review – hook doc block

- config/sync/block.block.os2loop_search_db_search_form.yml
- web/profiles/custom/os2loop/themes/os2loop_theme/assets/app.scss
- web/profiles/custom/os2loop/themes/os2loop_theme/assets/comment.scss
- web/profiles/custom/os2loop/themes/os2loop_theme/assets/search.scss
- web/profiles/custom/os2loop/themes/os2loop_theme/os2loop_theme.theme
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--post.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--question-answers.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/form--views-exposed-form-os2loop-search-db-page-search-form.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/form--views-exposed-form-os2loop-search-db-page-search.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/form-element--search-api-autocomplete.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/input--textfield.html.twig
https://jira.itkdev.dk/browse/LOOP-737
- LOOP-737: Show search form only on node view
- LOOP-737: Highlight current comment
- LOOP-737: Cleaned up search form display
> LOOP-737: Search form improvements

- web/profiles/custom/os2loop/src/Helper/Helper.php
Allows users to view content even when the content type is disabled.
> LOOP-874: Fixed view node access check

- web/profiles/custom/os2loop/themes/os2loop_theme/assets/icons.scss
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/links--comment.html.twig
https://jira.itkdev.dk/browse/LOOP-897
Fixes issue with translated css classes.
With Danish as site language:
(before)
(after)
> LOOP-897: Fixed styling of comment buttons

- config/sync/language.types.yml
https://jira.itkdev.dk/browse/LOOP-898
Users should not be able to select ui language. This is removes the check for user language when detecting the language.
> LOOP-898: Remove user language from detection

- web/profiles/custom/os2loop/modules/os2loop_section_page/modules/os2loop_section_page_fixtures/src/Fixture/FrontPageFixture.php
- web/profiles/custom/os2loop/themes/os2loop_theme/assets/search.scss
- web/profiles/custom/os2loop/themes/os2loop_theme/yarn.lock
https://jira.itkdev.dk/browse/LOOP-895
Hides search box clear symbol from chromium browsers.
> LOOP-895: Search field styling

- config/sync/core.entity_form_display.node.os2loop_documents_collection.default.yml
- config/sync/core.entity_form_display.node.os2loop_documents_document.default.yml
- config/sync/core.entity_form_display.node.os2loop_external.default.yml
- config/sync/core.entity_form_display.node.os2loop_page.default.yml
- config/sync/core.entity_form_display.node.os2loop_post.default.yml
- config/sync/core.entity_form_display.node.os2loop_question.default.yml
- config/sync/core.entity_form_display.node.os2loop_section_page.default.yml
https://jira.itkdev.dk/browse/LOOP-908
Removes fields that are not used from the node edit form.
> LOOP-908: Removed “Promote” and “Sticky” from node forms

- web/profiles/custom/os2loop/modules/os2loop_flag_content/README.md
- web/profiles/custom/os2loop/modules/os2loop_flag_content/os2loop_flag_content.routing.yml
- web/profiles/custom/os2loop/modules/os2loop_flag_content/os2loop_flag_content.services.yml
- web/profiles/custom/os2loop/modules/os2loop_flag_content/os2loop_flag_content.tokens.inc
- web/profiles/custom/os2loop/modules/os2loop_flag_content/src/Form/FlagContentForm.php
- web/profiles/custom/os2loop/modules/os2loop_flag_content/src/Form/SettingsForm.php
- web/profiles/custom/os2loop/modules/os2loop_flag_content/src/Helper/MailHelper.php
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/content-tasks.html.twig
https://jira.itkdev.dk/browse/LOOP-750
> LOOP-750: added tokens to flag content mailhelper

- web/profiles/custom/os2loop/themes/os2loop_theme/templates/block/block--system-branding-block.html.twig
https://jira.itkdev.dk/browse/LOOP-925
Including the logo fails when it's not an svg. This changes to embed (via `<img/>`) logo rather than include.
> LOOP-925: Embedded site logo

- config/sync/core.entity_form_display.node.os2loop_documents_collection.default.yml
- config/sync/core.entity_view_display.node.os2loop_documents_collection.default.yml
- config/sync/core.entity_view_display.node.os2loop_documents_collection.list_display.yml
- config/sync/core.entity_view_display.node.os2loop_documents_collection.os2loop_search_db_search_autocomplete.yml
- config/sync/core.entity_view_display.node.os2loop_documents_collection.pdf.yml
- config/sync/core.entity_view_display.node.os2loop_documents_collection.search_result.yml
- config/sync/core.entity_view_display.node.os2loop_documents_collection.teaser.yml
- config/sync/field.field.node.os2loop_documents_collection.os2loop_shared_approval_date.yml
- config/sync/field.field.node.os2loop_documents_collection.os2loop_shared_approver.yml
- config/sync/field.field.node.os2loop_documents_collection.os2loop_shared_owner.yml
- config/sync/field.field.node.os2loop_documents_collection.os2loop_shared_version.yml
- config/sync/field.storage.node.os2loop_shared_approval_date.yml
- config/sync/field.storage.node.os2loop_shared_approver.yml
- config/sync/field.storage.node.os2loop_shared_owner.yml
- config/sync/field.storage.node.os2loop_shared_version.yml
- web/profiles/custom/os2loop/modules/os2loop_documents/modules/os2loop_documents_fixtures/src/Fixture/CollectionFixture.php
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-collection.html.twig
https://jira.itkdev.dk/browse/LOOP-930
Adds metadata fields to document collections. For consistency with “Revision data”, additional metadata fields are shared (namewise) as they may be used on other content types.
- LOOP-930: Added metadata fields
- LOOP-930: Added metadata in collection fixture
- LOOP-930: Added metadata in collection template
> LOOP-930: Metadata fields

- config/sync/user.role.os2loop_user_administrator.yml
https://jira.itkdev.dk/browse/LOOP-874
Allows `administrator` to manage themes.
> LOOP-874: Allowed administrator to manage theme

- web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/menu--main.html.twig
https://jira.itkdev.dk/browse/LOOP-935
Fixes issue with handling of external urls in menu links.
```
UnexpectedValueException: External URLs do not have an internal route name. in Drupal\Core\Url->getRouteName() (line 564 of core/lib/Drupal/Core/Url.php).
twig_get_attribute() (Line: 107)
__TwigTemplate_ee23866e074fe3d26a259494ab6f4eff6b3219a5448742477e5b7384cb6254e7->macro_menu_links() (Line: 1110)
…
```
> LOOP-935: Fixed check for route name on menu link with external url

- config/sync/config_ignore.settings.yml
https://jira.itkdev.dk/browse/LOOP-874
Ignores OS2Loop Member list config when importing config.
> LOOP-874: Added member list settings to config ignore

- CHANGELOG.md
- web/profiles/custom/os2loop/themes/os2loop_theme/assets/navbar.scss
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/menu--main.html.twig
https://jira.itkdev.dk/browse/LOOP-948﻿
New position:
Mobile menu:
> Position fix for user menu dropdown

- web/profiles/custom/os2loop/themes/os2loop_theme/assets/documents.scss
https://jira.itkdev.dk/browse/LOOP-1034
Changes
into
> LOOP-1034: Updated table styling

- web/profiles/custom/os2loop/modules/os2loop_media/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-1118
Adds a workaround for
```
2021/09/17 12:19:59 [error] 121641#121641: *86496 FastCGI sent in stderr: "PHP message: Uncaught PHP Exception LogicException: "The database connection is not serializable. This probably means you are serializing an object that has an indirect reference to the database connection. Adjust your code so that is not necessary. Alternatively, look at DependencySerializationTrait as a temporary solution."
```
> LOOP-1118: Added DependencySerializationTrait to form helper

- config/sync/core.entity_view_display.media.os2loop_media_file.media_library.yml
- config/sync/views.view.media.yml
- config/sync/views.view.media_library.yml
- web/profiles/custom/os2loop/modules/os2loop_media/src/Plugin/Field/FieldFormatter/FileImageFormatter.php
https://jira.itkdev.dk/browse/LOOP-1035﻿
> LOOP-1035: Add custom fieldformatter for file fields to display a styled image if possible

- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--list-display.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--list-display.html.twig
https://jira.itkdev.dk/browse/LOOP-1161﻿
> LOOP-1161: Added timestamp to lists

- web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/user-info.html.twig
https://jira.itkdev.dk/browse/LOOP-1171
Tweaks display of anonymous author.
Before
After
> LOOP-1171: Tweaked display of anonymous author

- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-document.html.twig
- web/profiles/custom/os2loop/translations/translations.da.po
https://jira.itkdev.dk/browse/LOOP-1220
Fixes missing display of list of collections a document is part of (if no collection context is defined by the url):
> LOOP-1220: Fixed display of collection list

- config/sync/core.entity_form_display.paragraph.os2loop_documents_highlighted_co.default.yml
- config/sync/core.entity_form_display.paragraph.os2loop_documents_step.default.yml
- config/sync/core.entity_form_display.paragraph.os2loop_documents_step_by_step.default.yml
- config/sync/core.entity_form_display.paragraph.os2loop_documents_table.default.yml
- config/sync/core.entity_form_display.paragraph.os2loop_documents_text_and_image.default.yml
- config/sync/core.entity_view_display.paragraph.os2loop_documents_highlighted_co.default.yml
- config/sync/core.entity_view_display.paragraph.os2loop_documents_step.default.yml
- config/sync/core.entity_view_display.paragraph.os2loop_documents_step_by_step.default.yml
- config/sync/core.entity_view_display.paragraph.os2loop_documents_table.default.yml
- config/sync/core.entity_view_display.paragraph.os2loop_documents_text_and_image.default.yml
- config/sync/field.field.paragraph.os2loop_documents_highlighted_co.os2loop_documents_toc_ignore.yml
- config/sync/field.field.paragraph.os2loop_documents_step.os2loop_documents_step_title.yml
- config/sync/field.field.paragraph.os2loop_documents_step_by_step.os2loop_documents_toc_ignore.yml
- config/sync/field.field.paragraph.os2loop_documents_table.os2loop_documents_toc_ignore.yml
- config/sync/field.field.paragraph.os2loop_documents_text_and_image.os2loop_documents_toc_ignore.yml
- config/sync/field.storage.paragraph.os2loop_documents_toc_ignore.yml
- config/sync/language/da/field.field.paragraph.os2loop_documents_highlighted_co.os2loop_documents_toc_ignore.yml
- config/sync/language/da/field.field.paragraph.os2loop_documents_step_by_step.os2loop_documents_toc_ignore.yml
- config/sync/language/da/field.field.paragraph.os2loop_documents_table.os2loop_documents_toc_ignore.yml
- config/sync/language/da/field.field.paragraph.os2loop_documents_text_and_image.os2loop_documents_toc_ignore.yml
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/os2loop_documents_title.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/paragraph--os2loop-documents-highlighted-co.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/paragraph--os2loop-documents-step-by-step.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/paragraph--os2loop-documents-table.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/paragraph--os2loop-documents-text-and-image.html.twig
https://jira.itkdev.dk/browse/LOOP-1221
Adds “Ignore in table of contents” to document paragraphs
> LOOP-1221: Added TOC ignore field to document paragraphs

- web/profiles/custom/os2loop/themes/os2loop_theme/assets/app.js
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-collection.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-document.html.twig
https://jira.itkdev.dk/browse/LOOP-1237
Makes external links (starting with `http://` er `https://`) in main content in documents and document collections open in new tabs (`target="_blank"`).
> LOOP-1237: Make external links open in new tab

- web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/field--os2loop-documents-info-box.html.twig
https://jira.itkdev.dk/browse/LOOP-1227
Before:
After:
> LOOP-1227: Removed alert styling from info box

- web/profiles/custom/os2loop/themes/os2loop_theme/assets/components/layout/title.scss
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/field--node--os2loop-shared-profession.html.twig
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/macros.html.twig
https://jira.itkdev.dk/browse/LOOP-1245
Change behaviour of bagdes to wrap inside container
After:
Before:
> LOOP-1245: Wrap badges instead of inline.

- web/profiles/custom/os2loop/themes/os2loop_theme/assets/components/pdf/pdf.scss
- web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/paragraph--os2loop-documents-step.html.twig
https://jira.itkdev.dk/browse/SUPP0RT-644
Fixes display of step title
Before
After
> SUPP0RT-644: Fixed step title display in pdf

- docker-compose.yml
https://jira.itkdev.dk/browse/SUPP0RT-650
Adds phpfpm image with wkhtmltopdf.
Note: Using the Traefik setup from https://github.com/itk-dev/devops_itkdev-docker (or something similar) is required to actually test PDF generation due to the NGINX docker container not being directly accessible from the PHP container:
```
Error generating document: Failed to generate PDF: Loading pages …
Warning: Failed to load http://0.0.0.0:54182/sites/default/files/css/css_EGKleuQUDoNwiPUbxRf90uVNi3ODyf8p0ucqeltCO2w.css (ignore)
…
```
> SUPP0RT-650: Added phpfpm image with wkhtmltopdf

- web/profiles/custom/os2loop/modules/os2loop_user_login/src/Helper/Helper.php
https://jira.itkdev.dk/browse/SUPP0RT-821
Disables cache on `userlogin` form to prevent redirect to default login method.
> SUPP0RT-821: Disabled userlogin form cache

- CHANGELOG.md
- web/profiles/custom/os2loop/themes/os2loop_theme/assets/app.scss
- web/profiles/custom/os2loop/themes/os2loop_theme/assets/components/elements/step-by-step.scss
https://leantime.itkdev.dk/tickets/showKanban#/tickets/showTicket/1124
- Add space after paragraphs
- Add space between images in a step in step-by-step
Result:
> 1124: Fix spacing

- CHANGELOG.md
- README.md
- web/profiles/custom/os2loop/modules/os2loop_section_page/modules/os2loop_section_page_fixtures/src/Fixture/FrontPageFixture.php
Added new fixture for the frontpage
Updated Readme
added coding stadard fixes
> Fixture frontpage

- data-export/export_document_collections_with_meta.sql
- data-export/export_documents_with_meta.sql
- data-export/export_external_with_meta.sql
- data-export/export_folding_parts_of_documents.sql
- data-export/export_news_posts_with_meta.sql
- data-export/export_q_and_a_with_meta.sql
- data-export/export_static_pages_with_meta.sql
Also adds some comments, since the queries are copied from itk-ai/loop_vectorstore develop branch
> Add status true condition

- .github/PULL_REQUEST_TEMPLATE.md
- .woodpecker/stg.yml
- CHANGELOG.md
- docker-compose.override.yml
- docker-compose.server.override.yml
https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/4184
Added support for automatic deployment to test site,
N/A
If your code does not pass all the requirements on the checklist you have to add a comment explaining why this change
should be exempt from the list.
N/A
> Automatic deployment to test site

- .github/workflows/build_release.yml
- .woodpecker/os2forms_prod.yml
- CHANGELOG.md
- config/sync/config_ignore.settings.yml
https://leantime.itkdev.dk/?tab=timesheet#/tickets/showTicket/4184
* Updated config ignore base on current live prod sites changed config.
N/A
If your code does not pass all the requirements on the checklist you have to add a comment explaining why this change
should be exempt from the list.
N/A
> OS2 forms auto-deployment (woodpecker)
