itk-dev/os2loop

config/sync/core.extension.yml, config/sync/field.field.paragraph.os2loop_section_page_views_refer.os2loop_section_page_view.yml, config/sync/statistics.settings.yml, config/sync/views.view.os2loop_section_page_most_viewed.yml
https://jira.itkdev.dk/browse/LOOP-735
=> LOOP-735: Added statistics module and view

web/profiles/custom/os2loop/modules/os2loop_section_page/README.md, web/profiles/custom/os2loop/modules/os2loop_section_page/modules/os2loop_section_page_fixtures/os2loop_section_page_fixtures.info.yml, web/profiles/custom/os2loop/modules/os2loop_section_page/modules/os2loop_section_page_fixtures/os2loop_section_page_fixtures.services.yml, web/profiles/custom/os2loop/modules/os2loop_section_page/modules/os2loop_section_page_fixtures/src/Fixture/SectionPageFixture.php, web/profiles/custom/os2loop/modules/os2loop_section_page/os2loop_section_page.info.yml, web/profiles/custom/os2loop/modules/os2loop_section_page/os2loop_section_page.module
https://jira.itkdev.dk/browse/LOOP-735
Adds fixtures for section pages.
=> LOOP-735: Added section page fixtures

config/sync/search_api.index.os2loop_search_db_index.yml
https://jira.itkdev.dk/browse/LOOP-832
=> LOOP-832: Enabled html_filter on search index

.github/workflows/pr.yaml, README.md, composer.json, phpcs.xml.dist, web/profiles/custom/os2loop/modules/os2loop_documents/modules/os2loop_documents_fixtures/os2loop_documents_fixtures.info.yml, web/profiles/custom/os2loop/modules/os2loop_documents/modules/os2loop_documents_fixtures/src/Fixture/DocumentFixture.php, web/profiles/custom/os2loop/modules/os2loop_documents/modules/os2loop_documents_tests/os2loop_documents_tests.info.yml, web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.info.yml, web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/CollectionHelper.php, web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/FormHelper.php, web/profiles/custom/os2loop/modules/os2loop_external/modules/os2loop_external_fixtures/os2loop_external_fixtures.info.yml, web/profiles/custom/os2loop/modules/os2loop_external/os2loop_external.info.yml, web/profiles/custom/os2loop/modules/os2loop_page/modules/os2loop_page_fixtures/os2loop_page_fixtures.info.yml, web/profiles/custom/os2loop/modules/os2loop_page/os2loop_page.info.yml, web/profiles/custom/os2loop/modules/os2loop_post/README.draft.md, web/profiles/custom/os2loop/modules/os2loop_post/modules/os2loop_post_fixtures/os2loop_post_fixtures.info.yml, web/profiles/custom/os2loop/modules/os2loop_post/os2loop_post.info.yml, web/profiles/custom/os2loop/modules/os2loop_question/modules/os2loop_question_fixtures/os2loop_question_fixtures.info.yml, web/profiles/custom/os2loop/modules/os2loop_question/os2loop_question.info.yml, web/profiles/custom/os2loop/modules/os2loop_search_db/os2loop_search_db.info.yml, web/profiles/custom/os2loop/modules/os2loop_section_page/modules/os2loop_section_page_fixtures/os2loop_section_page_fixtures.info.yml, web/profiles/custom/os2loop/modules/os2loop_taxonomy/modules/os2loop_taxonomy_fixtures/os2loop_taxonomy_fixtures.info.yml, web/profiles/custom/os2loop/modules/os2loop_taxonomy/os2loop_taxonomy.info.yml, web/profiles/custom/os2loop/modules/os2loop_upvote/modules/os2loop_upvote_fixtures/os2loop_upvote_fixtures.info.yml, web/profiles/custom/os2loop/modules/os2loop_upvote/modules/os2loop_upvote_fixtures/os2loop_upvote_fixtures.services.yml, web/profiles/custom/os2loop/modules/os2loop_upvote/modules/os2loop_upvote_fixtures/src/Fixture/UpvoteFixture.php, web/profiles/custom/os2loop/modules/os2loop_upvote/os2loop_upvote.info.yml, web/profiles/custom/os2loop/modules/os2loop_user/modules/os2loop_user_fixtures/os2loop_user_fixtures.info.yml, web/profiles/custom/os2loop/modules/os2loop_user/os2loop_user.info.yml, web/profiles/custom/os2loop/os2loop.info.yml
https://jira.itkdev.dk/browse/LOOP-844
- Applies Drupal practice coding standards
=> LOOP-844: Changes after external code review – coding standards

web/profiles/custom/os2loop/modules/os2loop_post/modules/os2loop_post_fixtures/os2loop_post_fixtures.services.yml, web/profiles/custom/os2loop/modules/os2loop_post/modules/os2loop_post_fixtures/src/Fixture/MedicinFixture.php
https://jira.itkdev.dk/browse/LOOP-858
Adds post data to test search with match in either content or subject name (or both).
=> LOOP-858: Added “medicin” fixture

web/profiles/custom/os2loop/modules/os2loop_menu/README.md, web/profiles/custom/os2loop/modules/os2loop_menu/modules/os2loop_menu_fixtures/os2loop_menu_fixtures.info.yml, web/profiles/custom/os2loop/modules/os2loop_menu/modules/os2loop_menu_fixtures/os2loop_menu_fixtures.services.yml, web/profiles/custom/os2loop/modules/os2loop_menu/modules/os2loop_menu_fixtures/src/Fixture/MainMenuFixture.php, web/profiles/custom/os2loop/modules/os2loop_section_page/modules/os2loop_section_page_fixtures/src/Fixture/SectionPageFixture.php
https://jira.itkdev.dk/browse/LOOP-858
=> LOOP-858: Added main menu fixtures

web/profiles/custom/os2loop/modules/os2loop_flag_content/src/Form/FlagContentForm.php
https://jira.itkdev.dk/browse/LOOP-750
=> LOOP-750: added node label to flag form content

web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/FormHelper.php
https://jira.itkdev.dk/browse/LOOP-869
- LOOP-869: Fixed extraction of document id
- LOOP-869: Added info on documents in new collection
=> LOOP-869: Document collections

config/sync/language/da/views.view.content.yml, config/sync/language/da/views.view.files.yml, config/sync/language/da/views.view.user_admin_people.yml, config/sync/views.view.content.yml, config/sync/views.view.files.yml, config/sync/views.view.user_admin_people.yml
https://jira.itkdev.dk/browse/LOOP-869
=> LOOP-869: Added admin views

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/filter.format.os2loop_documents_body.yml, config/sync/filter.format.os2loop_page.yml, web/profiles/custom/os2loop/modules/os2loop_post/modules/os2loop_post_fixtures/src/Fixture/PostFixture.php
https://jira.itkdev.dk/browse/LOOP-873
- LOOP-873: Fixed text format in fixture
- LOOP-873: Renamed text format
- LOOP-873: Added “Convert Legacy Media Tags to Markup” to legacy content
=> LOOP-873: Text formats

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/views.view.content.yml, config/sync/views.view.user_admin_people.yml
https://jira.itkdev.dk/browse/LOOP-758
Adds export (CSV and XLSX) to the content and user lists.
=> LOOP-758: Export of content and user lists

web/profiles/custom/os2loop/modules/os2loop_subscriptions/os2loop_subscriptions.module
https://jira.itkdev.dk/browse/LOOP-899
=> LOOP-899: Added empty array to theme hook

web/profiles/custom/os2loop/modules/os2loop_menu/modules/os2loop_menu_fixtures/src/Fixture/MainMenuFixture.php, web/profiles/custom/os2loop/modules/os2loop_menu/os2loop_menu.info.yml, web/profiles/custom/os2loop/modules/os2loop_menu/os2loop_menu.links.menu.yml
- Removed front page link from main menu
- Removed superfluous user menu from menu fixture
=> Menu cleanup

web/profiles/custom/os2loop/themes/os2loop_theme/assets/form.scss, web/profiles/custom/os2loop/themes/os2loop_theme/os2loop_theme.theme, web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/container--edit-os2loop-shared-subject-wrapper.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/input--radio.html.twig
https://jira.itkdev.dk/browse/LOOP-889
- Change styling of autocomplete deluxe
-﻿Change html of radios
=> LOOP-889: Changed display of radios and autocomplete deluxe fields

web/profiles/custom/os2loop/themes/os2loop_theme/assets/icons.scss
https://jira.itkdev.dk/browse/LOOP-894
=> LOOP-737: Changed answer icon. Cleaned up.

config/sync/block.block.os2loop_theme_page_title.yml, config/sync/views.view.contact_list.yml, config/sync/views.view.os2loop_messages.yml, config/sync/views.view.os2loop_section_page_most_viewed.yml, config/sync/views.view.os2loop_section_page_newest_content.yml, config/sync/views.view.os2loop_section_page_user_favourites.yml, config/sync/views.view.os2loop_subscription_term.yml, config/sync/views.view.os2loop_subscriptions_node.yml, config/sync/views.view.os2loop_user_answers.yml, config/sync/views.view.os2loop_user_questions.yml, web/profiles/custom/os2loop/themes/os2loop_theme/os2loop_theme.theme, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/user.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/views/views-view--os2loop-messages--attachment-1.html.twig
https://jira.itkdev.dk/browse/LOOP-910﻿
=> LOOP-910: Changed config for views and set page title for user

web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/pager.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/views/views-mini-pager.html.twig
https://jira.itkdev.dk/browse/LOOP-910﻿
=> LOOP-910: Added pager styling

config/sync/core.entity_view_display.user.user.card_display.yml, config/sync/core.entity_view_display.user.user.list_display.yml, web/profiles/custom/os2loop/modules/os2loop_mail_notifications/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-743
Minor fixes and cleanup.
=> LOOP-743: Mail notifications

config/sync/core.entity_form_display.comment.os2loop_question_answer.default.yml, config/sync/core.entity_view_display.comment.os2loop_question_answer.default.yml, config/sync/core.entity_view_display.comment.os2loop_question_answer.list_display.yml, config/sync/core.entity_view_display.comment.os2loop_question_answer.os2loop_search_db_search_autocomplete.yml, config/sync/core.entity_view_display.comment.os2loop_question_answer.search_result.yml, config/sync/field.field.comment.os2loop_question_answer.os2loop_question_answer_media.yml, config/sync/field.storage.comment.os2loop_question_answer_media.yml, web/profiles/custom/os2loop/modules/os2loop_question/modules/os2loop_question_fixtures/src/Fixture/AnswerFixture.php, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--os2loop-question-answers.html.twig
https://jira.itkdev.dk/browse/LOOP-916
Adds media field to answers.
=> LOOP-916: Added media field to answers

config/sync/os2loop_flag_content.settings.yml, config/sync/os2loop_share_with_a_friend.settings.yml, config/sync/os2loop_subscriptions.settings.yml, web/profiles/custom/os2loop/modules/os2loop_flag_content/os2loop_flag_content.module, web/profiles/custom/os2loop/modules/os2loop_flag_content/os2loop_flag_content.services.yml, web/profiles/custom/os2loop/modules/os2loop_flag_content/src/Form/FlagContentForm.php, web/profiles/custom/os2loop/modules/os2loop_flag_content/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_flag_content/src/Helper/Helper.php, web/profiles/custom/os2loop/modules/os2loop_share_with_a_friend/os2loop_share_with_a_friend.module, web/profiles/custom/os2loop/modules/os2loop_share_with_a_friend/os2loop_share_with_a_friend.services.yml, web/profiles/custom/os2loop/modules/os2loop_share_with_a_friend/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_share_with_a_friend/src/Helper/Helper.php, web/profiles/custom/os2loop/modules/os2loop_subscriptions/os2loop_subscriptions.links.menu.yml, web/profiles/custom/os2loop/modules/os2loop_subscriptions/os2loop_subscriptions.module, web/profiles/custom/os2loop/modules/os2loop_subscriptions/os2loop_subscriptions.routing.yml, web/profiles/custom/os2loop/modules/os2loop_subscriptions/os2loop_subscriptions.services.yml, web/profiles/custom/os2loop/modules/os2loop_subscriptions/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_subscriptions/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-918
- LOOP-918: Fixed typo
- LOOP-918: Added node type setting for Flag content
- LOOP-918: Added node type setting for Share with a friend
- LOOP-918: Added node type setting for subscriptions
=> LOOP-918: Grants and settings

web/profiles/custom/os2loop/themes/os2loop_theme/assets/form.scss
https://jira.itkdev.dk/browse/LOOP-909
Adds visual marker to required fields.
=> LOOP-909: Added visual marker to required input fields

config/sync/config_ignore.settings.yml, web/profiles/custom/os2loop/themes/os2loop_theme/assets/color-templates/blue.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/color-templates/default.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/color-templates/green.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/color-templates/red.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/color-templates/yellow.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/colors.scss, web/profiles/custom/os2loop/themes/os2loop_theme/os2loop_theme.theme, web/profiles/custom/os2loop/themes/os2loop_theme/webpack.config.js
https://jira.itkdev.dk/browse/LOOP-856﻿
=> LOOP-856: Added color templates

web/profiles/custom/os2loop/themes/os2loop_theme/assets/icons.scss
https://jira.itkdev.dk/browse/LOOP-890﻿
=> LOOP-890: CHanged share icon

web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/user.html.twig
https://jira.itkdev.dk/browse/LOOP-911﻿
=> LOOP-911: Added user image

config/sync/core.entity_form_display.node.os2loop_documents_collection.default.yml, config/sync/core.entity_form_display.node.os2loop_documents_document.default.yml, config/sync/core.entity_view_display.node.os2loop_documents_collection.default.yml, config/sync/core.entity_view_display.node.os2loop_documents_collection.list_display.yml, config/sync/core.entity_view_display.node.os2loop_documents_collection.os2loop_search_db_search_autocomplete.yml, config/sync/core.entity_view_display.node.os2loop_documents_collection.pdf.yml, config/sync/core.entity_view_display.node.os2loop_documents_collection.search_result.yml, config/sync/core.entity_view_display.node.os2loop_documents_collection.teaser.yml, config/sync/core.entity_view_display.node.os2loop_documents_document.default.yml, config/sync/core.entity_view_display.node.os2loop_documents_document.list_display.yml, config/sync/core.entity_view_display.node.os2loop_documents_document.os2loop_search_db_search_autocomplete.yml, config/sync/core.entity_view_display.node.os2loop_documents_document.pdf.yml, config/sync/core.entity_view_display.node.os2loop_documents_document.search_result.yml, config/sync/core.entity_view_display.node.os2loop_documents_document.teaser.yml, config/sync/field.field.node.os2loop_documents_collection.os2loop_documents_info_box.yml, config/sync/field.field.node.os2loop_documents_document.os2loop_documents_info_box.yml, config/sync/field.storage.node.os2loop_documents_info_box.yml, web/profiles/custom/os2loop/modules/os2loop_documents/modules/os2loop_documents_fixtures/os2loop_documents_fixtures.services.yml, web/profiles/custom/os2loop/modules/os2loop_documents/modules/os2loop_documents_fixtures/src/Fixture/CollectionLegacyFixture.php, web/profiles/custom/os2loop/modules/os2loop_documents/modules/os2loop_documents_fixtures/src/Fixture/DocumentLegacyFixture.php, web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/FormHelper.php, web/profiles/custom/os2loop/themes/os2loop_theme/assets/app.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/colors.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/documents.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-collection.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-document.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/field--os2loop-documents-info-box.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/yarn.lock
https://jira.itkdev.dk/browse/LOOP-853
Adds info box to legacy document and collections.
=> LOOP-853: Added info box to documents and collections

web/profiles/custom/os2loop/themes/os2loop_theme/assets/app.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/font.scss, web/profiles/custom/os2loop/themes/os2loop_theme/package.json
https://jira.itkdev.dk/browse/LOOP-914﻿
=> LOOP-914: Smoked font

web/profiles/custom/os2loop/themes/os2loop_theme/assets/colors.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/search.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/field--os2loop-shared-subject.html.twig
- Fine tune search results and focus effect
- Coding standards
=> Finetune search results

web/profiles/custom/os2loop/themes/os2loop_theme/assets/app.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/navbar.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/block/block--system-branding-block.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/user--card-display.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/user--list-display.html.twig
https://jira.itkdev.dk/browse/LOOP-933﻿
=> Inline style cleanup

web/profiles/custom/os2loop/themes/os2loop_theme/assets/documents.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/search.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/user.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--list-display.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-collection.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-document.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/macros.html.twig
https://jira.itkdev.dk/browse/LOOP-934﻿
=> LOOP-934: Moved table of contents macro, removed user fields, fixed icon bug

config/sync/views.view.os2loop_messages.yml
https://jira.itkdev.dk/browse/LOOP-952﻿
=> LOOP-952: Disabled messages read view

web/profiles/custom/os2loop/modules/os2loop_flag_content/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_mail_notifications/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_member_list/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_question/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_search_db/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_settings/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_share_with_a_friend/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_subscriptions/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_user_login/src/Form/SettingsForm.php
Flushes all caches when saving OS2Loop settings.
=> Flushed caches when saving OS2Loop settings

CHANGELOG.md, web/profiles/custom/os2loop/modules/os2loop_subscriptions/templates/os2loop-subscriptions-user.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/assets/member-view.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/flag--os2loop-subscription-term.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/taxonomy-term--list-display.html.twig
https://jira.itkdev.dk/browse/LOOP-949﻿
With new styling:
=> Styling subscriptions page

CHANGELOG.md, web/profiles/custom/os2loop/themes/os2loop_theme/assets/member-view.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/flag--message-read.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/message.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/views/views-view-unformatted--os2loop-messages--page-1.html.twig
https://jira.itkdev.dk/browse/LOOP-950﻿
With new styling:
=> Styling messages list

CHANGELOG.md, web/profiles/custom/os2loop/themes/os2loop_theme/assets/_user.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/app.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/search.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/user.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/field--user--os2loop-user-biography.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/user-info.html.twig
https://jira.itkdev.dk/browse/LOOP-947﻿
Added styling for the user profile page
=> Styling user profile page

web/profiles/custom/os2loop/modules/os2loop_user_login/src/Helper/Helper.php
Please add a link to the issue being addressed by this change.
Please include a short description of the suggested change and the reasoning behind the approach you have chosen.
If your change affects the user interface you should include a screenshot of the result with the pull request.
If you have any further comments or questions for the reviewer them please add them here.
=> Move SAML login to top of user login form

web/profiles/custom/os2loop/themes/os2loop_theme/assets/_collapse.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/app.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/search.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/block/block--facet-block--os2loop-search-db-content-type.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/facets-item-list--os2loop-search-db-document.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/form--views-exposed-form-os2loop-search-db-page-search.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/form-element--edit-search-api-fulltext--2.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/form-element--edit-sort-by--2.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/form-element--edit-sort-order--2.html.twig
https://jira.itkdev.dk/browse/LOOP-946﻿
=> Search filters

config/sync/config_ignore.settings.yml, config/sync/core.extension.yml, config/sync/os2loop_cookies.settings.yml, web/profiles/custom/os2loop/modules/os2loop_cookies/README.md, web/profiles/custom/os2loop/modules/os2loop_cookies/modules/os2loop_cookie_information/README.md, web/profiles/custom/os2loop/modules/os2loop_cookies/modules/os2loop_cookie_information/os2loop_cookie_information.info.yml, web/profiles/custom/os2loop/modules/os2loop_cookies/modules/os2loop_cookie_information/os2loop_cookie_information.module, web/profiles/custom/os2loop/modules/os2loop_cookies/modules/os2loop_cookie_information/os2loop_cookie_information.services.yml, web/profiles/custom/os2loop/modules/os2loop_cookies/modules/os2loop_cookie_information/src/Helper/FormHelper.php, web/profiles/custom/os2loop/modules/os2loop_cookies/os2loop_cookies.info.yml, web/profiles/custom/os2loop/modules/os2loop_cookies/os2loop_cookies.links.menu.yml, web/profiles/custom/os2loop/modules/os2loop_cookies/os2loop_cookies.routing.yml, web/profiles/custom/os2loop/modules/os2loop_cookies/src/Form/SettingsForm.php, web/profiles/custom/os2loop/themes/os2loop_theme/templates/layout/html.html.twig
https://jira.itkdev.dk/browse/LOOP-753﻿
=> Cookie module

web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/CollectionHelper.php, web/profiles/custom/os2loop/modules/os2loop_question/src/Form/SettingsForm.php
https://jira.itkdev.dk/browse/LOOP-954
- LOOP-954: Added function needed by migration
- LOOP-954: Added informative description to field
=> Minor change and improvement related to migration

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/views.view.os2loop_search_db.yml
Adds auto-submit to search form.
=> Added auto-submit to search form

web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.module, web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.services.yml, web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/CollectionHelper.php, web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/FormHelper.php, web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/NodeHelper.php
https://jira.itkdev.dk/browse/LOOP-957
Prevents deletion of documents used in collections.
=> LOOP-957: Prevented deletion of documents

composer.json, composer.lock, config/sync/language/da/user.mail.yml, config/sync/samlauth.authentication.yml, config/sync/system.advisories.yml, config/sync/system.rss.yml, config/sync/user.mail.yml, config/sync/views.settings.yml, web/README.md
https://jira.itkdev.dk/browse/LOOP-958
Update packages and related config
```
- Upgrading drupal/core-dev (9.1.10 => 9.2.0)
- Upgrading drupal/core-recommended (9.1.10 => 9.2.0)
- Upgrading drupal/gin_login (1.0.0-rc7 => 1.0.0-rc8): Extracting archive
- Upgrading drupal/externalauth (1.3.0 => 1.4.0): Extracting archive
- Upgrading drupal/samlauth (3.2.0 => 3.3.0): Extracting archive
```
=> LOOP-958: Updated core and contrib

.markdownlint.json, README.md, docs/configuring-os2loop.md, docs/modules.md, web/profiles/custom/os2loop/modules/os2loop_subscriptions/README.md, web/profiles/custom/os2loop/modules/os2loop_user_login/README.md
@todo
Adds documentation on modules and documentation.
=> Add module and configuration documentation

web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/NodeHelper.php
https://jira.itkdev.dk/browse/LOOP-958
=> LOOP-958: Added account check

web/profiles/custom/os2loop/themes/os2loop_theme/templates/macros.html.twig
https://jira.itkdev.dk/browse/LOOP-990
=> LOOP-990: Fixed collection TOC display

config/sync/views.view.os2loop_search_db.yml
https://jira.itkdev.dk/browse/LOOP-989
Set default search result order to most relevant result first.
=> LOOP-989: Update default search result order

web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/content-tasks.html.twig
https://jira.itkdev.dk/browse/LOOP-975
=> LOOP-975: Added check for node id in template

web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/paragraph--os2loop-documents-highlighted-co.html.twig
https://jira.itkdev.dk/browse/LOOP-975
=> LOOP-975: Fixed template for preview

web/profiles/custom/os2loop/modules/os2loop_user_login/os2loop_user_login.services.yml, web/profiles/custom/os2loop/modules/os2loop_user_login/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-972﻿
=> LOOP-972: Added redirect on user login

web/profiles/custom/os2loop/modules/os2loop_settings/src/Settings.php
https://jira.itkdev.dk/browse/LOOP-983﻿
=> LOOP-983: CHanged check for active vocabulary

docs/configuring-os2loop.md, web/profiles/custom/os2loop/modules/os2loop_settings/src/Form/SettingsForm.php
https://jira.itkdev.dk/browse/LOOP-1005
=> LOOP-1005: Exposed select site settings for administrator

web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--os2loop-post-comments.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--os2loop-question-answers.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/comment-tasks.html.twig
https://jira.itkdev.dk/browse/LOOP-984﻿
=> LOOP-984: Added template for comment icons

config/sync/views.view.contact_list.yml, web/profiles/custom/os2loop/themes/os2loop_theme/templates/views/views-view--contact-list--page-1.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/views/views-view--contact-list--page-2.html.twig
https://jira.itkdev.dk/browse/LOOP-976
﻿
=> LOOP-976: CHanged filters for contact list and hid display

config/sync/os2loop_flag_content.settings.yml
https://jira.itkdev.dk/browse/LOOP-985
=> LOOP-985: Changed template for mail

config/sync/core.entity_view_display.media.os2loop_media_image.default.yml, config/sync/core.entity_view_display.user.user.compact.yml
https://jira.itkdev.dk/browse/LOOP-986﻿
=> LOOP-149: Added image to content

web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--os2loop-post-comments.html.twig
https://jira.itkdev.dk/browse/LOOP-984﻿
=> LOOP-984: Added missing entity in twig

web/profiles/custom/os2loop/modules/os2loop_user_login/README.md, web/profiles/custom/os2loop/modules/os2loop_user_login/os2loop_user_login.module, web/profiles/custom/os2loop/modules/os2loop_user_login/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_user_login/src/Helper/Helper.php, web/profiles/custom/os2loop/themes/os2loop_theme/templates/block/block--user-login-block.html.twig
https://jira.itkdev.dk/browse/LOOP-1010
Adds option for setting default login method.
- LOOP-1010: Added default (automatic) login method
- LOOP-1010: Fixed typos
=> LOOP-1010: Auto login

docs/configuring-os2loop.md
=> Added info on main menu items

web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-document.html.twig
https://jira.itkdev.dk/browse/LOOP-1020
=> LOOP-1020: Hide “About collection” on documents not in a collection

web/profiles/custom/os2loop/themes/os2loop_theme/assets/documents.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-document.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/macros.html.twig
https://jira.itkdev.dk/browse/LOOP-1017
=> LOOP-1017: Add link on document collection title

web/profiles/custom/os2loop/modules/os2loop_user_login/os2loop_user_login.info.yml, web/profiles/custom/os2loop/modules/os2loop_user_login/os2loop_user_login.module, web/profiles/custom/os2loop/modules/os2loop_user_login/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_user_login/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-1012
Adds option to hide log out menu item.
=> LOOP-1012: Added option to hide log out menu item

web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-collection.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-document.html.twig
https://jira.itkdev.dk/browse/LOOP-1018﻿
=> LOOP-1018: CHanged order of taxonomies

web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--os2loop-post-comments.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--os2loop-question-answers.html.twig
https://jira.itkdev.dk/browse/LOOP-1015﻿
=> LOOP-1015: Added date to include

config/sync/views.view.user_admin_people.yml
https://jira.itkdev.dk/browse/LOOP-1019﻿
=> LOOP-1019: Changed user admin view

web/profiles/custom/os2loop/themes/os2loop_theme/templates/block/block--facet-block.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/form/facets-item-list--os2loop-search-db-document.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/search/facets-item-list--checkbox.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/search/facets-result-item--checkbox.html.twig
https://jira.itkdev.dk/browse/LOOP-1014﻿
=> LOOP-1014: Changed templates for search filters

config/sync/field.field.node.os2loop_post.os2loop_shared_profession.yml
https://jira.itkdev.dk/browse/LOOP-1021
=> LOOP-1021: Made profession optional on post

composer.lock, config/sync/config_ignore.settings.yml, config/sync/entity_print.settings.yml, config/sync/os2loop_documents.settings.yml, web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.info.yml, web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.links.menu.yml, web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.module, web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.routing.yml, web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.services.yml, web/profiles/custom/os2loop/modules/os2loop_documents/src/Controller/EntityPrintController.php, web/profiles/custom/os2loop/modules/os2loop_documents/src/EventSubscriber/EntityPrintEventSubscriber.php, web/profiles/custom/os2loop/modules/os2loop_documents/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/NodeHelper.php, web/profiles/custom/os2loop/modules/os2loop_documents/templates/os2loop-documents-pdf-footer.html.twig, web/profiles/custom/os2loop/modules/os2loop_documents/templates/os2loop-documents-pdf-header.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/assets/pdf/_layout.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/pdf/pdf.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-collection--pdf.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-documents-document--pdf-content.html.twig
https://jira.itkdev.dk/browse/LOOP-1016
Adds header and footer to pdf.
Adds OS2Loop Documents settings with pdf footer image.
[WIP] Update styling
=> LOOP-1016: Pdf styling

web/profiles/custom/os2loop/modules/os2loop_post/os2loop_post.module, web/profiles/custom/os2loop/modules/os2loop_post/os2loop_post.services.yml, web/profiles/custom/os2loop/modules/os2loop_post/src/Helper/Helper.php, web/profiles/custom/os2loop/modules/os2loop_question/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-1045
=> LOOP-1045: Removed preview on comments

web/profiles/custom/os2loop/themes/os2loop_theme/assets/navbar.scss
https://jira.itkdev.dk/browse/LOOP-1062
=> LOOP-1062: Added styling for main menu active

config/sync/core.entity_form_display.user.user.default.yml, config/sync/language/da/field.field.user.user.os2loop_user_areas_of_expertise.yml
https://jira.itkdev.dk/browse/LOOP-1065
=> LOOP-1065: Updated translation on user profile

config/sync/user.role.os2loop_user_administrator.yml
https://jira.itkdev.dk/browse/LOOP-1053
=> LOOP-1053:Changed admin permissions

config/sync/field.field.user.user.os2loop_mail_notifications_intvl.yml
https://jira.itkdev.dk/browse/LOOP-1077
=> LOOP-1077: Changed notification interval

web/profiles/custom/os2loop/modules/os2loop_subscriptions/src/EventSubscriber/SubscriptionFlagSubscriber.php
https://jira.itkdev.dk/browse/LOOP-1076
=> LOOP-1076: CHanged check on active messages

web/profiles/custom/os2loop/modules/os2loop_search_db/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-1078
Disables search result cache to make processors work as expected.
=> LOOP-1078: Disable search result cache

web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/FormHelper.php
https://jira.itkdev.dk/browse/LOOP-1084
Checks that a document is actually part of a collection before stating that it cannot be deleted.
=> Check for non-empty collections

web/profiles/custom/os2loop/themes/os2loop_theme/README.md, web/profiles/custom/os2loop/themes/os2loop_theme/assets/colors.scss, web/profiles/custom/os2loop/themes/os2loop_theme/os2loop_theme.theme
https://jira.itkdev.dk/browse/LOOP-1085
- LOOP-1085: Made theme colors overridable for real
- LOOP-1085: Added cache flush on theme settings submit
=> Menu color

web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/menu--main.html.twig
https://jira.itkdev.dk/browse/LOOP-1092
=> LOOP-1092: Fixed menu url check

web/profiles/custom/os2loop/modules/os2loop_user/os2loop_user.module, web/profiles/custom/os2loop/modules/os2loop_user/os2loop_user.services.yml, web/profiles/custom/os2loop/modules/os2loop_user/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-1093
Allows only select user roles to edit user mail.
=> LOOP-1093: Restricted access to user mail

web/profiles/custom/os2loop/modules/os2loop_mail_notifications/os2loop_mail_notifications.module, web/profiles/custom/os2loop/modules/os2loop_mail_notifications/os2loop_mail_notifications.services.yml, web/profiles/custom/os2loop/modules/os2loop_mail_notifications/src/Form/SettingsForm.php, web/profiles/custom/os2loop/modules/os2loop_mail_notifications/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-1119
=> LOOP-1119: Added configurable default user notification interval

config/sync/core.entity_form_display.paragraph.os2loop_documents_table.default.yml, config/sync/core.entity_view_display.paragraph.os2loop_documents_table.default.yml, config/sync/editor.editor.os2loop_documents_table.yml, config/sync/field.field.node.os2loop_documents_document.os2loop_documents_document_conte.yml, config/sync/field.field.paragraph.os2loop_documents_table.field_os2loop_documents_tbl_cont.yml, config/sync/field.field.paragraph.os2loop_documents_table.field_os2loop_documents_tbl_desc.yml, config/sync/field.storage.paragraph.field_os2loop_documents_tbl_cont.yml, config/sync/field.storage.paragraph.field_os2loop_documents_tbl_desc.yml, config/sync/filter.format.os2loop_documents_table.yml, config/sync/language/da/editor.editor.os2loop_documents_table.yml, config/sync/language/da/paragraphs.paragraphs_type.os2loop_documents_table.yml, config/sync/paragraphs.paragraphs_type.os2loop_documents_table.yml, config/sync/user.role.os2loop_user_document_author.yml, config/sync/user.role.os2loop_user_document_collection_editor.yml, web/profiles/custom/os2loop/modules/os2loop_documents/css/ckeditor.css, web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.module, web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.services.yml, web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/Helper.php, web/profiles/custom/os2loop/themes/os2loop_theme/assets/documents.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/field--os2loop-documents-document-conte.html.twig
https://jira.itkdev.dk/browse/LOOP-1097
- LOOP-1097: Added table paragraph
- LOOP-1097: Added spacing between paragraphs
=> LOOP-1097: Table paragraph

web/profiles/custom/os2loop/modules/os2loop_toc_block/src/Plugin/Block/TocBlock.php
https://jira.itkdev.dk/browse/LOOP-1079
Makes TOC block title optional.
=> LOOP-1079: Hacked optional title on TOC block

web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/field--os2loop-documents-info-box.html.twig
https://jira.itkdev.dk/browse/LOOP-1087
=> LOOP-1087: Made quickbox color match subject color

config/sync/views.view.os2loop_user_answers.yml
https://jira.itkdev.dk/browse/LOOP-1143﻿
=> LOOP-1143: Changed order of replies

web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/pager.html.twig
https://jira.itkdev.dk/browse/LOOP-1058﻿
=> LOOP-1058: Changed pager element

web/profiles/custom/os2loop/themes/os2loop_theme/assets/app.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/helper-classes.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--list-display.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-post--list-display.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-question--list-display.html.twig
https://jira.itkdev.dk/browse/LOOP-1154﻿
=> LOOP-1154: Added replace filter for none breaking space in some content.

config/sync/flag.flag.message_read.yml, config/sync/views.view.os2loop_messages.yml
https://jira.itkdev.dk/browse/LOOP-1144
=> LOOP-1144: Changed view

web/profiles/custom/os2loop/modules/os2loop_mail_notifications/src/Helper/MailHelper.php
https://jira.itkdev.dk/browse/LOOP-1158
Fixes handling of revision messages in mail content.
=> LOOP-1158: Fixed handling of revision messages in mail content

config/sync/views.view.os2loop_user_answers.yml
https://jira.itkdev.dk/browse/LOOP-1143﻿
=> LOOP-1143: Changed order of lists

config/sync/field.field.node.os2loop_documents_collection.os2loop_documents_info_box.yml, config/sync/language/da/field.field.node.os2loop_documents_collection.os2loop_documents_info_box.yml
https://jira.itkdev.dk/browse/LOOP-1087
Renames “Quickbox” to “Highlighted content” (“Fremhævet indhold” in Danish).
=> LOOP-1087: Rename Quickbox

config/sync/language/da/paragraphs.paragraphs_type.os2loop_documents_highlighted_co.yml
https://jira.itkdev.dk/browse/LOOP-1087
Changed the translation of highlighted content (in danish) from 'promoveret indhold' to 'fremhævet indhold'
=> Loop-1087: Changed translation

config/sync/field.field.node.os2loop_documents_document.os2loop_documents_document_conte.yml, web/profiles/custom/os2loop/modules/os2loop_oembed/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-1132﻿
=> LOOP-1132: Added video paragraph to documents

composer.json, composer.lock
- Applied security update to Drupal core (9.2.9)
- Updated openid_connect version contraint
=> Core and module upgrade

web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/user-info.html.twig
https://jira.itkdev.dk/browse/LOOP-1145
Cleans up user info template.
=> LOOP-1145: Cleaned up template

config/sync/language/da/block.block.os2loop_search_db_category.yml, config/sync/language/da/field.field.node.os2loop_documents_collection.os2loop_shared_category.yml, config/sync/language/da/field.field.node.os2loop_documents_document.os2loop_shared_category.yml, config/sync/language/da/field.field.node.os2loop_external.os2loop_shared_category.yml, config/sync/language/da/field.field.node.os2loop_post.os2loop_shared_category.yml, config/sync/language/da/field.field.node.os2loop_question.os2loop_shared_category.yml
https://jira.itkdev.dk/browse/LOOP-906
Translates “Category” to “Kategori” in Danish.
=> LOOP-906: Added Danish translation of “Category”

web/profiles/custom/os2loop/themes/os2loop_theme/assets/taxonomy-colors.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/paragraph--os2loop-documents-highlighted-co.html.twig
https://jira.itkdev.dk/browse/LOOP-1087
Adds light background color to info boxes (including “Highlighted content”).
=> LOOP-1087: Added light background color to info boxes

config/sync/user.role.os2loop_user_administrator.yml, config/sync/user.role.os2loop_user_document_collection_editor.yml, web/profiles/custom/os2loop/modules/os2loop_messages/os2loop_messages.permissions.yml, web/profiles/custom/os2loop/modules/os2loop_messages/os2loop_messages.services.yml, web/profiles/custom/os2loop/modules/os2loop_messages/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-904﻿
=> LOOP-904: Added permission to view notify users checkbox

config/sync/language/da/views.view.content.yml, config/sync/views.view.content.yml
https://jira.itkdev.dk/browse/LOOP-1047﻿
=> LOOP-1047: Changed admin list

composer.json, composer.lock
https://jira.itkdev.dk/browse/LOOP-1163﻿
=> LOOP-1163: Add fix for bug in lnline entity form

config/sync/os2loop_alert.settings.yml, web/profiles/custom/os2loop/modules/os2loop_alert/os2loop_alert.info.yml, web/profiles/custom/os2loop/modules/os2loop_alert/src/Form/AlertForm.php, web/profiles/custom/os2loop/modules/os2loop_alert/src/Form/SettingsForm.php
https://jira.itkdev.dk/browse/LOOP-907
Disables preview of important message (!)
=> LOOP-907: Disabled preview of important message

web/profiles/custom/os2loop/themes/os2loop_theme/assets/icons.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/tabs.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/title.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--os2loop-post-comments.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--os2loop-question-answers.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-external.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-post.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content/node--os2loop-question.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/field--node--os2loop-question-answers.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/field--os2loop-post-comments.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/user-info.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/macros.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/comment-tasks.html.twig
https://jira.itkdev.dk/browse/LOOP-1160﻿
=> LOOP-1160: Change templates and remove absolute positioning of icons

web/profiles/custom/os2loop/modules/os2loop_oembed/src/TwigExtension/TwigExtension.php
https://jira.itkdev.dk/browse/LOOP-1132﻿
=> LOOP-1132: Added fullscreen attribute

web/profiles/custom/os2loop/modules/os2loop_alert/src/Form/AlertForm.php
https://jira.itkdev.dk/browse/LOOP-907
Show preview only after clicking “Preview message”
=> LOOP-907: Handled message preview

config/sync/field.field.paragraph.os2loop_video.os2loop_video_iframe.yml, config/sync/field.field.paragraph.os2loop_video.os2loop_video_url.yml, config/sync/field.field.paragraph.os2loop_video.os2loop_video_width.yml, config/sync/field.storage.paragraph.os2loop_video_source_type.yml, config/sync/language/da/field.field.paragraph.os2loop_video.os2loop_video_description.yml, config/sync/language/da/field.field.paragraph.os2loop_video.os2loop_video_iframe.yml, config/sync/language/da/field.field.paragraph.os2loop_video.os2loop_video_source_type.yml, config/sync/language/da/field.field.paragraph.os2loop_video.os2loop_video_url.yml, config/sync/language/da/field.field.paragraph.os2loop_video.os2loop_video_width.yml, config/sync/language/da/field.storage.paragraph.os2loop_video_source_type.yml, web/profiles/custom/os2loop/modules/os2loop_oembed/src/TwigExtension/TwigExtension.php
https://jira.itkdev.dk/browse/LOOP-1132
Updates video field names and descriptions. Adds missing translations to Danish.
=> LOOP-1132: Updated video field names and stuff

config/sync/os2loop_alert.settings.yml
Fixes link in message template
https://jira.itkdev.dk/browse/LOOP-907
=> Update os2loop_alert.settings.yml (LOOP-907)

web/profiles/custom/os2loop/modules/os2loop_messages/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-1170
Generates messages only on published content.
=> Generate messages only on published content

web/profiles/custom/os2loop/modules/os2loop_oembed/src/TwigExtension/TwigExtension.php
https://jira.itkdev.dk/browse/LOOP-1166
=> LOOP-1166: Added dreambroker as option

web/profiles/custom/os2loop/modules/os2loop_upvote/src/Helper/FlagHelper.php, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--os2loop-post-comments.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/comment--os2loop-question-answers.html.twig
https://jira.itkdev.dk/browse/LOOP-1171
Fixes assignment of `top-comment` CSS class.
=> LOOP-1171: Fixed assignment of top-comment CSS class

config/sync/language/da/field.field.comment.os2loop_post_comment.os2loop_comment_anonymous_author.yml, config/sync/language/da/field.field.comment.os2loop_question_answer.os2loop_comment_anonymous_author.yml
https://jira.itkdev.dk/browse/LOOP-1174
=> LOOP-1174: Added missing config translations

web/profiles/custom/os2loop/themes/os2loop_theme/assets/color-templates/lightblue.scss, web/profiles/custom/os2loop/themes/os2loop_theme/os2loop_theme.theme, web/profiles/custom/os2loop/themes/os2loop_theme/webpack.config.js
https://jira.itkdev.dk/browse/LOOP-1191
=> LOOP-1191: Added lightblue theme

config/sync/filter.format.os2loop_documents_table.yml
https://jira.itkdev.dk/browse/LOOP-1190
=> LOOP-1190: Allowed p in tables

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/filter.format.os2loop_documents_body.yml
Adds [toc] filter on document body.
=> TOC filter on document body field

config/sync/field.field.paragraph.os2loop_documents_table.os2loop_documents_tbl_cont.yml
https://jira.itkdev.dk/browse/LOOP-1196
Updates default table content.
=> LOOP-1196: Default template content

config/sync/user.role.os2loop_user_document_author.yml
https://jira.itkdev.dk/browse/LOOP-1198
=> Changed permissions for document authors

web/profiles/custom/os2loop/modules/os2loop_upvote/os2loop_upvote.services.yml, web/profiles/custom/os2loop/modules/os2loop_upvote/src/EventSubscriber/UpvoteFlagSubscriber.php
https://jira.itkdev.dk/browse/LOOP-1195
=> LOOP-1195: Added event subscriber

web/profiles/custom/os2loop/themes/os2loop_theme/templates/navigation/menu--main.html.twig
https://jira.itkdev.dk/browse/LOOP-1224
=> LOOP-1224: Fixed handling of menu item urls

web/profiles/custom/os2loop/modules/os2loop_section_page/src/Helper/FormHelper.php
https://jira.itkdev.dk/browse/LOOP-1226
=> LOOP-1226: Fixed hiding of block reference options

composer.json, composer.lock, config/sync/toc_api.toc_type.default.yml, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/paragraph--os2loop-documents-highlighted-co.html.twig
https://jira.itkdev.dk/browse/LOOP-1221
Excludes highlighted content from table of contents.
=> LOOP-1221: Excluded highlighed content from table of contents

config/sync/editor.editor.os2loop_documents_table.yml, config/sync/language/da/editor.editor.os2loop_documents_table.yml
https://jira.itkdev.dk/browse/LOOP-1228
Adds table style in editor
=> LOOP-1228: Added table style

web/profiles/custom/os2loop/themes/os2loop_theme/assets/app.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/color-templates/blue.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/color-templates/lightblue.scss, web/profiles/custom/os2loop/themes/os2loop_theme/assets/variables/colors.scss, web/profiles/custom/os2loop/themes/os2loop_theme/test/colors.php
https://jira.itkdev.dk/browse/LOOP-1227
=> LOOP-1227: Updated theme colors

config/sync/block.block.os2loop_search_db_search_form.yml, config/sync/block.block.os2loop_theme_page_title.yml, config/sync/block.block.os2loop_theme_primary_local_tasks.yml, config/sync/core.entity_form_display.comment.os2loop_post_comment.default.yml, config/sync/core.entity_form_display.comment.os2loop_question_answer.default.yml, config/sync/core.entity_form_display.node.os2loop_documents_document.default.yml, config/sync/core.entity_form_display.node.os2loop_post.default.yml, config/sync/core.entity_form_display.node.os2loop_question.default.yml, config/sync/core.entity_form_display.user.user.default.yml, config/sync/core.entity_form_display.user.user.register.yml, config/sync/core.entity_view_display.comment.os2loop_post_comment.default.yml, config/sync/core.entity_view_display.comment.os2loop_post_comment.list_display.yml, config/sync/core.entity_view_display.comment.os2loop_question_answer.default.yml, config/sync/core.entity_view_display.node.os2loop_documents_document.default.yml, config/sync/core.entity_view_display.node.os2loop_post.default.yml, config/sync/facets.facet.os2loop_search_db_content_type.yml, config/sync/field.storage.paragraph.os2loop_documents_step_title.yml, config/sync/filter.format.os2loop_documents_table.yml, config/sync/filter.format.os2loop_post.yml, config/sync/filter.format.os2loop_question_answer_rich_text.yml, config/sync/filter.format.os2loop_question_plain_text.yml, config/sync/filter.format.os2loop_question_rich_text.yml, config/sync/filter.format.os2loop_section_page.yml, config/sync/filter.format.plain_text.yml, config/sync/search_api.server.os2loop_search_db_server.yml, config/sync/system.site.yml, config/sync/views.view.contact_list.yml, config/sync/views.view.os2loop_search_db.yml, config/sync/views.view.os2loop_user_answers.yml
https://jira.itkdev.dk/browse/LOOP-1231
- LOOP-1231: Exported config
- LOOP-1231: Matched word start
=> LOOP-1231: Search config

web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/os2loop_documents_title.html.twig
https://jira.itkdev.dk/browse/LOOP-1233
Fixes error during generation of table of contents when a header is empty.
=> LOOP-1233: Fixed handling of empty headers

web/profiles/custom/os2loop/themes/os2loop_theme/assets/components/layout/body.scss
https://jira.itkdev.dk/browse/LOOP-1236
=> LOOP-1236: Unhid scrollbar

web/profiles/custom/os2loop/modules/os2loop_settings/os2loop_settings.module, web/profiles/custom/os2loop/modules/os2loop_settings/src/Helper/Helper.php
https://jira.itkdev.dk/browse/LOOP-1241
Before:
After:
=> LOOP-1241: Handled question menu items

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/language.content_settings.redirect.redirect.yml, config/sync/language/da/system.action.redirect_delete_action.yml, config/sync/language/da/views.view.redirect.yml, config/sync/redirect.settings.yml, config/sync/system.action.redirect_delete_action.yml, config/sync/views.view.redirect.yml
https://jira.itkdev.dk/browse/LOOP-1247
Adds Redirect module in order to handle changing content urls.
=> LOOP-1247: Added Redirect module

web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/user-info.html.twig
https://jira.itkdev.dk/browse/LOOP-1248
Fixes display of anonymous author.
=> LOOP-1248: Fixed display of anonymous user

config/sync/search_api.index.os2loop_search_db_index.yml
https://jira.itkdev.dk/browse/LOOP-1243
Includes step by step content in search index
=> LOOP-1243: Search API index configuration

composer.json, composer.lock, config/sync/core.extension.yml
https://jira.itkdev.dk/browse/SUPP0RT-644
Adds missing view_unpublished module (permissions were already in place).
=> SUPP0RT-644: Added and enabled view_unpublished module

web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/paragraph--os2loop-documents-step.html.twig
https://jira.itkdev.dk/browse/SUPP0RT-644
Includes step title in print.
=> SUPP0RT-644: Included step title in print

web/profiles/custom/os2loop/themes/os2loop_theme/templates/field/user-info.html.twig
https://jira.itkdev.dk/browse/SUPP0RT-662
Fixes issue with displaying user info on question answer with missing user.
=> SUPP0RT-662: Fixed issue with non-existing user

README.md, docker-compose.yml, web/profiles/custom/os2loop/themes/os2loop_theme/README.md, web/profiles/custom/os2loop/themes/os2loop_theme/assets/components/pdf/pdf.scss
https://jira.itkdev.dk/browse/SUPP0RT-650
Before:
After:
=> SUPP0RT-650: Fixed display of counters on steps in pdf

config/sync/core.entity_form_display.user.user.default.yml, config/sync/language/da/user.role.os2loop_user_manual.yml, config/sync/system.action.user_add_role_action.os2loop_user_manual.yml, config/sync/system.action.user_remove_role_action.os2loop_user_manual.yml, config/sync/theme_switcher.rule.edit_user_profile.yml, config/sync/user.role.os2loop_user_manual.yml, config/sync/user.role.os2loop_user_user_administrator.yml, web/profiles/custom/os2loop/modules/os2loop_messages/os2loop_messages.module, web/profiles/custom/os2loop/themes/os2loop_theme/assets/components/forms/user-form.scss, web/profiles/custom/os2loop/themes/os2loop_theme/templates/container--edit-account.html.twig, web/profiles/custom/os2loop/themes/os2loop_theme/templates/content-entities/user.html.twig
https://jira.itkdev.dk/browse/LOOP-1257
- LOOP-1257: Enabled account block
- LOOP-1257: Added manual user
- LOOP-1257: Allowed user administrator to set user roles
=> LOOP-1257: Manual user login

config/sync/search_api.index.os2loop_search_db_index.yml
https://jira.itkdev.dk/browse/SUPP0RT-763
Includes paragraph titles in search index. Cleans up search config a bit.
- SUPP0RT-763: Added paragraph title in search index
- SUPP0RT-763: Updated processor fields
- SUPP0RT-763: Added missing bundle boosts
=> SUPP0RT-763: Index paragraph title

web/profiles/custom/os2loop/themes/os2loop_theme/.editorconfig, web/profiles/custom/os2loop/themes/os2loop_theme/assets/app.js
https://jira.itkdev.dk/browse/SUPP0RT-764
Uses `scroll-padding-top` to prevent focused headings from hiding behind the header.
=> SUPP0RT-764: Table of contents

web/profiles/custom/os2loop/modules/os2loop_user_login/os2loop_user_login.services.yml, web/profiles/custom/os2loop/modules/os2loop_user_login/src/Helper/Helper.php
https://jira.itkdev.dk/browse/SUPP0RT-821
Fixes when the default login method is triggered.
=> SUPP0RT-821: Fixed handling of default login method

composer.json, composer.lock
https://jira.itkdev.dk/browse/LOOP-1261
Fixes the issue
```
Error: Call to a member function getFieldMapByFieldType() on null in …/web/modules/contrib/paragraphs_edit/src/Form/ParagraphCloneForm.php on line 140
```
when cloning a paragraph.
=> LOOP-1261: Update drupal/paragraphs_edit

.docker/data/.gitignore, .docker/data/README.md, .docker/nginx.conf, .docker/vhost.conf, .github/workflows/pr.yaml, CHANGELOG.md, README.md, docker-compose.dev.yml, docker-compose.redirect.yml, docker-compose.server.yml, docker-compose.yml, web/profiles/custom/os2loop/modules/os2loop_documents/modules/os2loop_documents_fixtures/os2loop_documents_fixtures.services.yml, web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.module, web/profiles/custom/os2loop/modules/os2loop_documents/os2loop_documents.services.yml, web/profiles/custom/os2loop/modules/os2loop_documents/src/Helper/CollectionHelper.php, web/profiles/custom/os2loop/modules/os2loop_mail_notifications/README.md, web/profiles/custom/os2loop/modules/os2loop_mail_notifications/os2loop_mail_notifications.module, web/profiles/custom/os2loop/modules/os2loop_mail_notifications/os2loop_mail_notifications.services.yml, web/profiles/custom/os2loop/modules/os2loop_messages/os2loop_messages.info.yml, web/profiles/custom/os2loop/modules/os2loop_messages/os2loop_messages.services.yml, web/profiles/custom/os2loop/modules/os2loop_messages/src/Helper/Helper.php
https://jira.itkdev.dk/browse/SUPP0RT-1100
The important stuff goes on in [`Drupal\os2loop_messages\Helper\Helper::createMessage()`](https://github.com/itk-dev/os2loop/blob/feature/SUPP0RT-1100-collection-subscription-notifications/web/profiles/custom/os2loop/modules/os2loop_messages/src/Helper/Helper.php#L78-L115).
- SUPP0RT-1100: Updated docker compose setup
- SUPP0RT-1100: Used class FQCN as services names
- SUPP0RT-1100: Created “collection changed” message when document is changed
- SUPP0RT-1100: Fixed typo
=> SUPP0RT-1100: Collection subscription notifications

config/sync/views.view.abonnenter_emner.yml
https://jira.itkdev.dk/browse/SUPP0RT-1161
Adds magic view.
Note: This is based on the [`hotfix/php-7.4`](https://github.com/itk-dev/os2loop/tree/hotfix/php-7.4) branch which is currently used in production.
=> SUPP0RT-1161: Added magic view

docker-compose.yml, web/profiles/custom/os2loop/modules/os2loop_mail_notifications/os2loop_mail_notifications.services.yml, web/profiles/custom/os2loop/modules/os2loop_mail_notifications/src/Helper/MailHelper.php
https://leantime.itkdev.dk/#/tickets/showTicket/830
Uses site default language (rather than user's prefered language) for notification messages.
=> Use site default language for notification messages

.docker/nginx.conf, .docker/templates/default.conf.template, docker-compose.dev.yml, docker-compose.redirect.yml, docker-compose.server.override.yml, docker-compose.server.yml, docker-compose.yml
https://leantime.itkdev.dk/#/tickets/showTicket/1046
- Updated docker compose setup
- Updated nginx configuration
=> docker compose updates

.github/workflows/pr.yaml, CHANGELOG.md, Taskfile.yml, task/Taskfile.yml
https://leantime.itkdev.dk/#/tickets/showTicket/1123
Fixes task and adds action for checking changelog.
=> Updated tasks

CHANGELOG.md, composer.json, composer.lock
https://leantime.itkdev.dk/#/tickets/showTicket/1913
- Upgrade drupal core (10.3.1)
- Change patch to match new core
=> Feature/upgrade drupal core 10.3.1

CHANGELOG.md, README.md, web/profiles/custom/os2loop/themes/os2loop_theme/assets/components/pdf/pdf.scss
https://leantime.itkdev.dk/#/tickets/showTicket/1964
=> Changed styles in pdf to ensure all paragraphs are displayed properly

CHANGELOG.md, README.md, composer.json, composer.lock
[#2212](https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/2212)
- Fix bug i toc_api
=> Added hotfix

CHANGELOG.md, composer.lock, web/sites/default/settings.php
=> Updated drupal core
